### ISSUE TITLE
Add option to ignore certain files

### ISSUE THREAD

**Issue by leoasis** [michalkvasnicak/babel-plugin-css-modules-transform#10]
In my current app I have some files that have global css, which are just required, and they are even only required in the server (guarded by an `if`). It'd be useful to be able to avoid attempting to transform those cases, probably by supporting the [ignore option](https://github.com/css-modules/css-modules-require-hook#ignore-functionregexstring) in the same way the require hook allows.

What do you think?

**Comment by michalkvasnicak** [comment]
Hello I am sorry for a delay but I don't have time currently. I will look at it but don't know when. But feel free to create a PR if you can :)
