### ISSUE TITLE
dont work for css-loader@^2

### ISSUE THREAD

**Issue by VadimZvf** [michalkvasnicak/babel-plugin-css-modules-transform#103]
classNames dont match with css-loader@2.0.0 or above
with css-loader@1.0.1 all fine

**Comment by felixcatto** [comment]
With css-loader@3.6.0 all works fine
I use `generateScopedName: '[local]--[hash:base64:5]',` in server babel config
and `localIdentName: '[local]--[hash:base64:5]',` in client (webpack) config

**Comment by felixcatto** [comment]
It turns out, in some cases classNames really don't match. But you can generate them by yourself.
_someFIle.js_
```
const crypto = require('crypto');

const generateScopedName = (localName, resourcePath) => {
  const getHash = value => crypto.createHash('sha256').update(value).digest('hex');
  const hash = getHash(`${resourcePath}${localName}`).slice(0, 5);
  return `${localName}__${hash}`;
};
```

_server babel config_
```
[
  'css-modules-transform',
  {
    generateScopedName,
    devMode: true,
  },
],
```


_client webpack config_
```
{
  loader: 'css-loader',
  options: {
    modules: {
      getLocalIdent: ({ resourcePath }, _, localName) => generateScopedName(localName, resourcePath),
    },
  },
},
```

**Comment by suhanw** [comment]
`classNames` don't match for me either, I'm using `css-loader@5.0.1` and `babel-plugin-css-modules-transform@1.6.2`
