### ISSUE TITLE
Problems on Windows machines

### ISSUE THREAD

**Issue by birdofpreyru** [michalkvasnicak/babel-plugin-css-modules-transform#110]
Because of https://github.com/css-modules/css-modules-require-hook/issues/119, `babel-plugin-css-modules-transform` does not work on Windows machines either (generates hashes different from those generated by `css-loader`). Part of the problem is that owner of `css-modules-require-hook` is not responsive (the issue and correct fix are pending for one year there). So, I am considering to fork and fix `css-modules-require-hook`, and wanna check with you @michalkvasnicak whether you are open to update this package to depend on my fixed version of `css-module-require-hook`?

**Comment by michalkvasnicak** [comment]
@birdofpreyru Hello I'm sorry I wasn't really invest my time into this package. I want to rewrite it to typescript and with babel 7 support only. I don't see any problem in supporting your library. Feel free to open PR for 1.x version to use your package.

**Comment by birdofpreyru** [comment]
Nevermind, I figured out I better fork your lib and give it a full revamp in my taste. If anybody needs it, I published my version here: https://www.npmjs.com/package/@dr.pogodin/babel-plugin-css-modules-transform
