### ISSUE TITLE
Is there a way to properly compile the source code using this plugin

### ISSUE THREAD

**Issue by Kannaj** [michalkvasnicak/babel-plugin-css-modules-transform#15]
The plugin seems to work only during runtime. for example , i can run it fine when i use the below

```
"start": "nodemon server/server.js --exec babel-node --plugins css-modules-transform",
```

however , when i try to compile the entire directory using babel-cli. 
```
"build": "babel server -d serverLib --plugins css-modules-transform"
````

i still get the css error. Is there anyway i can make it to work on the compiled version as well?

**Comment by michalkvasnicak** [comment]
What error are you getting? Because this plugin works just fine. I'm using it with babel-cli in several projects without problem.

**Comment by Kannaj** [comment]
this is the below error i get when i run the compiled version
```
[Error] SyntaxError: /home/avernus/Desktop/projects/node-sc-react/client/app.css: Unexpected token (1:0)
> 1 | .link{
    | ^
  2 |   text-decoration: none;
  3 |   border: 1px solid black;
  4 |   background-color: blue;
    at Parser.pp.raise (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseExprAtom (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/parser/expression.js:522:12)
    at Parser.parseExprAtom (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
    at Parser.pp.parseExprSubscripts (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/parser/expression.js:277:19)
    at Parser.pp.parseMaybeUnary (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/parser/expression.js:257:19)
    at Parser.pp.parseExprOps (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/parser/expression.js:188:19)
    at Parser.pp.parseMaybeConditional (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.parseMaybeAssign (/home/avernus/Desktop/projects/node-sc-react/node_modules/babylon/lib/plugins/flow.js:460:20)
```

does the plugin work only if its during run time?

**Comment by michalkvasnicak** [comment]
This plugin works with `babel-cli` too. I am using it to compile js code. 

I need to see javascript source file where is `app.css` imported and node.js version you are using. And if you are using `.babelrc` then past it here too.

But minimal project would be great so I can test it. It's weird that babel is actually opening css files for compilation but it shouldn't open it.

Maybe you are compiling only `server` directory and not `client` directory too? And some file from `server` directory is importing css file from `client`.

**Comment by Kannaj** [comment]
My app.jsx file 
```
import React from 'react';
import SignUp from './SignUp'

import style from './app.css'

class App extends React.Component{
  render(){
    return (
      <div>
        <p> Hello Kj</p>
          <a href="/auth/github" className="link">Sign up with github </a>
          <a href="/logout" className="logout"> Logout </a>
          <Link to ='/project'>Project</Link>
        <h1> {this.props.username} </h1>
        <h2> {this.props.email} </h2>
        <div> {this.props.children} </div>
      </div>
    )
  }
}
```

my .babelrc is for both the client and the server - so i'm not including the plugin here
```
{
  "presets" : ["es2015","react"]
}
```

my server file (only including the relevant parts - i'm not directly importing any component as such)
```
    match({ routes,location: req.url}, (err,redirect,renderProps) => {
      // console.log('redirect: ',redirect,' renderProps: ',renderProps)
      if (err) {
        console.error(err);
        return res.status(500).end('Internal server error');
      }
      if (!renderProps) return res.status(404).end('Not found');
      getInitialState(id_token)
        .then((initialState) => {
            const store = createStore(rootReducer,initialState);
            const html = renderToString(
              <Provider store={store}>

                  <RouterContext {...renderProps} />

              </Provider>
            );

            res.send(renderFullPage(html,initialState));
          })
        .catch(function(err){
          console.log('error: ',err)
        })
      });
  }

  const renderFullPage = (html,initialState) => {
    return `
      <!doctype html>
      <html>
        <head>
          <title>Redux Universal</title>
          <link rel="stylesheet" type="text/css" href="/main.css">
        </head>
        <body>
          <div id="app"><div>${html}</div></div>
          <script>
            window.__INITIAL_STATE__= ${JSON.stringify(initialState)}
          </script>
          <script src="/bundle.js"></script>
        </body>
      </html>`
  }
```

**Comment by michalkvasnicak** [comment]
You're using `ReactRouter` with server side render so it will import components. Probably you have components in `client` directory and server side files in `server` directory.

```
- project
   - /server
   - /client
```

You are compiling just `server` directory, but when server tries to render some component, it will import files from `client` directory which are not compiled. So you can try to compile directories with files that are used server side. Babel does not work like webpack (which is actually following `require` paths and compiles all files matching some plugins in plugins configuration).

**Comment by Kannaj** [comment]
So i should try by importing routes from the compiled 'bundle.js' file on the server side?

**Comment by michalkvasnicak** [comment]
No, you need to compile `client` directory using babel too. So you will have 2 build processes:

1. webpack will compile js files for browsers
2. babel will compile js files for node.js

**Comment by michalkvasnicak** [comment]
For example sometimes I am using following directory structure:

```
- /project_root
  - /server
  - /client
  - /shared
```

* `server` - contains only files used by node.js
* `client` - contains only files used by browser
* `shared` - contains files shared between node.js and browser (e.g. Components that are rendered server side and client side too)

But you can have a problem when you are importing files like `svg` or something other than `js, css` to component in shared directory. Because webpack will compile it using its plugins and babel no. So in that case I recommend you https://github.com/istarkov/babel-plugin-webpack-loaders

**Comment by Kannaj** [comment]
I'm sorry :( .. but that is exactly what i'm doing - i have a webpack.config.js for the client side. i run `webpack` - get the compiled bundle.js in my public directory. run `npm start`  which uses babel to compile the es6 server side code.

**Comment by michalkvasnicak** [comment]
Yes but you are compiling only `server` directory according to your definition from first comment `babel server -d serverLib --plugins css-modules-transform`. You need to compile `client` too.

**Comment by Kannaj** [comment]
ahh .. so the problem is im not using the same plugin for client as well right?

**Comment by Kannaj** [comment]
closing for now to try your suggestion .. will reopen if i still dont understand. .. thank you for your patience :)

**Comment by michalkvasnicak** [comment]
No, problem is that you are compiling just files in `server` directory and not in `client`. So those compiled files are using not compiled files from `client` directory.

`babel-node` works for you because it behaves like `babel-register` so it compiles all files you are `require`ing using defined babel plugins and presets. 

So if `babel-node` encounters a `require` it will try to compile a file if it's not ignored.

But `babel-cli` does not work that way. It just finds all files in given directory (in your case it is `server` directory). And compiles them using presets and plugins but does not **follow** files you are importing (using es6 `import` syntax) or `require()`ing. 

So for example if `babel-cli` encounters something like this:

```js
// this is server side file, lets assume that is is stored in src/server/index.js

const someComponent = require('../client/component.js');
```

It won't do anything with this code, because it is valid for node 5/6. So it will output it as is to `serverLib` directory.

Now when you run it using node.js, node.js runtime will actually require component.js. **But `component.js` is not compiled** so it will throw an error if this component contains something that node.js can not understand.

For example:

```js
// src/client/component.js
import styles from './styles.css';
```

This will throw an error because node.js does not natively support `import`.

If you have component like this:

```js
// src/client/component.js
const styles = require('./styles.css');
```

This will throw too because node.js cannot compile css file natively. 

So only solution to this is compile `client` directory too. But then you need to change output paths too.

So you'll have:

```
- /src
   - /server
   - /client
```

And you will configure babel to compile whole `src` dir and output it to `build` dir because you need to preserve file paths in javascript files. `babel src -d build --plugins css-modules-transform`

```
- /build
  - /server
  - /client
```

**Comment by Kannaj** [comment]
Thank you for the through explanation @michalkvasnicak :) . its clear now .. ill try your method

**Comment by willdembinski** [comment]
Hi im have this issue - but its happening to me at run time.

My Error:
```
SyntaxError: /home/pil0t/Projects/powr_x/src/client/components/GetStartedView/style.scss: Unexpected token (5:0)
  3 | 
  4 | 
> 5 | .gsView {
    | ^
  6 |   // display: none;
  7 |   background-color: $secondary-color;
  8 |   height: 100%;
```

My package.json scripts:
```
  "scripts": {
    "dbinit": "node ./utils/setup/createdb.js",
    "dbusercreate": "node ./utils/setup/create_powr_user.js",
    "_test": "// mocha --compilers js:babel-register",
    "test": "export NODE_ENV=\"test\" && mocha ./utils/test/test_setup.js --require ignore-styles",
    "lint": "eslint src",
    "start": " babel-node ./src/api/server.js --presets es2015,stage-2 --plugins css-modules-transform",
    "_start": "node ./src/api/server.js",
    "go": "export NODE_ENV=\"development\" && nodemon ./src/api/server.js --exec babel-node --presets es2015,stage-2",
    "postinstall": "node ./deploy.js",
    "component": "node ./utils/components/component_script.js"
  },

```

My .babelrc:
```
{
  "presets": ["react", "es2015","stage-2"],
  "plugins": [
    "babel-plugin-webpack-alias",
    ["transform-object-rest-spread", { "useBuiltIns": true }],
    ["css-modules-transform",{
        "extensions": [".scss"],
        "generateScopedName": "[name]__[local]___[hash:base64:5]",
        "preprocessCss": "./utils/sass_preprocess_tool.js",
        "extractCss": "./dist/combined.css"
    }]
  ]
}
```
Running `npm start` results in the error.  I would love any guidance that I can get. Very confused :(

**Comment by willdembinski** [comment]
Here's my preprocess script:
```
var sass = require('node-sass');
var path = require('path');

module.exports = function (data, filename) {
    var result;
    result = sass.renderSync({
        data: data,
        file: filename
    }).css;

    return result.toString('utf8');
};

```

**Comment by michalkvasnicak** [comment]
@willdembinski I am not sure but maybe try to change your `start` script in `package.json` to `babel-node ./src/api/server.js` I think this will load `.babelrc` so there is no need to specify plugins again. I'm not sure if `babel-node` will merge `.babelrc` with the arguments from the command line.

**Comment by willdembinski** [comment]
@michalkvasnicak - Literally ecstatic that you got back to me.  Thank you so much. So with just running:`"start": "babel-node ./src/api/server.js --presets es2015,stage-2"` - it errors for some reason no being able to locate the preProcesscss script.

```
/home/pil0t/Projects/powr_x/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

Error: /home/pil0t/Projects/powr_x/src/api/server.js: Cannot find module './utils/sass_preprocess_tool.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireLocalFileOrNodeModule (/home/pil0t/Projects/powr_x/node_modules/babel-plugin-css-modules-transform/build/utils/requireLocalFileOrNodeModule.js:24:16)
```

**Comment by willdembinski** [comment]
But with the `--plugins css-modules-transform` flag.  It seemingly get farther - ultimately error-ing in the css file.  Maybe my problem is the `--plugins` flag is causing it to ignore whats in the babelrc, NOT having the preprocess module, then error-ing in css file?

**Comment by willdembinski** [comment]
Also - it throws the same error when using an absolute file path for the location of the preprocess script. sad panda :(

**Comment by michalkvasnicak** [comment]
@willdembinski yeah it seems that if you specify it using `--plugins` then it is ignoring settings for plugin from `.babelrc`. 

Have you tried to specify absolute path in `.babelrc` and run it without `--plugins` so `.babelrc` is picked up?

**Comment by willdembinski** [comment]
Forget what I said about the absolute file path - when i use an absolute path i get:

```
/home/pil0t/Projects/powr_x/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:578
        throw err;
        ^

Error: /home/pil0t/Projects/powr_x/utils/sass_preprocess_tool.js: Configuration file for 'preprocessCss' is not exporting a function
    at Object.preprocessCss (/home/pil0t/Projects/powr_x/node_modules/babel-plugin-css-modules-transform/build/options_resolvers/preprocessCss.js:25:15)
    at /home/pil0t/Projects/powr_x/node_modules/babel-plugin-css-modules-transform/build/index.js:131:66
    at Array.forEach (native)
```

**Comment by willdembinski** [comment]
The module is exporting a blank object.  Which is indicative of a circular dependency?

**Comment by michalkvasnicak** [comment]
It's really strange you are getting this error. I don't see any circular dependency. If you run `node ./utils/sass_preprocess_tool.js` it works without any problem?

**Comment by willdembinski** [comment]
Yes sir :( I can import it and it is the desired function.  I just reinstalled all the node modules.  It gave this error:
```
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall babel
    npm install babel-cli
```
Followed those instructions, same error about the module exporting a blank object. :(

Error:
```
/home/pil0t/Projects/powr_x/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:578
        throw err;
        ^

Error: /home/pil0t/Projects/powr_x/utils/sass_preprocess_tool.js: Configuration file for 'preprocessCss' is not exporting a function
```

**Comment by michalkvasnicak** [comment]
Could you try to compile your scripts so you can run your app using `node` and not `babel-node`? Maybe `babel-node` is the reason why it does not work but I am not sure.

**Comment by willdembinski** [comment]
I will give that a shot.  But to confirm - I'm expecting to to still error on the .scss file correct? If it doesnt - then something truly magical is happening?

**Comment by michalkvasnicak** [comment]
It shouldn't error on `.scss` file because now it is trying to import your preprocess file but it has some problem with circular dependencies probably. And if this is really caused by circular dependencies then I am not sure how it is possible because you don't have any requires in your preprocess file. So maybe it is caused by some `babel-node` require hook.

**Comment by willdembinski** [comment]
It successfully compiles everything in a file.

**Comment by michalkvasnicak** [comment]
And does it work when you run it using `node` ?

**Comment by willdembinski** [comment]
One moment - I have some stupid require issue.  Fixing.

**Comment by willdembinski** [comment]
Yea - i guess Im a total babel noob.  My relative require statements are destroying everything. I am fail.

**Comment by willdembinski** [comment]
I think you got me on a good track - Im gonna try this working with it for a bit before bothering.  I really appreciate you taking the time to help <3 Very much appreciated.

**Comment by willdembinski** [comment]
Yes sir.  Did that.  How does babel handle file paths?  I should probably read the literature more before asking questions like that.

**Comment by willdembinski** [comment]
Ah - the entire directory should be compiled. Thank you again for the help.

**Comment by willdembinski** [comment]
Alright - totally able to run the compiled version when my head is not place firmly in my @$$.  I will maybe try using an older version of babel-node or something?  Do you think thats a decent course of action?

**Comment by michalkvasnicak** [comment]
Not really sure if it will help. I'm not familiar enough with `babel-node` internals. Maybe try to use only this plugin in your `.babelrc` with `babel-node` and if you get same behaviour (circle dependency) then it is caused by logic in `babel-node`.

**Comment by Saravanakumar46** [comment]
@michalkvasnicak  , Hai ..  Am getting the same error where Kannaj was mentioned in his second comment . My Error is  : babel-core is trying to parse my css .. am doing server side rendering .. as u said i was compiling only Server not client that's why am facing this error . . here my question is how can i set client compilation . This is my Start command is package.json ---> "babel-node src/js/server"

**Comment by Saravanakumar46** [comment]
This is my Folder Structure -->-                                                                                                                  App
 -Js
   - /server
   - /client
