### ISSUE TITLE
Updated css-modules-require-hook

### ISSUE THREAD

**Issue by nordsimon** [michalkvasnicak/babel-plugin-css-modules-transform#18]
Hello

A merge was made on the css-modules-require-hook. It fixed issues I'm having with scoped npm packages. So if you would like to bump the current version to 4.0.2 instead of 4.0.1 it would be fantastic

in package.json
`"css-modules-require-hook": "^4.0.1",`
to
`"css-modules-require-hook": "^4.0.2",`

**Comment by michalkvasnicak** [comment]
Ok I've done it. But I don't think that was necessary, because version signature is `^4.0.1` so it should update to newest version when you run `npm update`. If it did not, then just remove module from `node_modules` dir and rerun `npm update`.

**Comment by nordsimon** [comment]
Sure. I didn't run update though, just remove and another install. Thanks anyway
