### ISSUE TITLE
camelCase option works differently from css-loader?camelCase

### ISSUE THREAD

**Issue by AmBeta** [michalkvasnicak/babel-plugin-css-modules-transform#28]
I use this babel plugin on server side, while using webpack css-loader on client side, to get css modules work in an isomorphic app.

I want to keep my classes in dashed style in css files, so I turn on the `camelCase` option on both side.   
But they result in different class names.

This is my CSS:

```
// style.css
.bordered-box {
  border: 1px solid #ddd;
  min-height: 60px;
  padding: 1px 3px;
}
```

The server side result: `<div class="style__borderedBox___1CfFu"></div>`
The client side result: `<div class="style__bordered-box___2hkXK"></div>`

This is my babel plugin config:

```
["css-modules-transform", {
  "generateScopedName": "[name]__[local]___[hash:base64:5]",
  "extensions": [".css", ".less"],
  "camelCase": true,
  "preprocessCss": "./less-require-hook.js"
}]
```

And this is my webpack loaders config:

```
{
  test: /\.css$/,
  loaders: [
    "style-loader",
    "css-loader?modules&camelCase&localIdentName=[name]__[local]___[hash:base64:5]"
  ]
}
```

**Comment by michalkvasnicak** [comment]
Have you tried replacing `localIdentName` by `generateScopedName` in `css-loader` query string?

What version of `webpack` and `css-loader` are you using?

**Comment by michalkvasnicak** [comment]
What's  the correct result you want? The server side output or client side output? Because from what I see, you are enabling the `camelCase` so server side is correct but client side is not.

**Comment by AmBeta** [comment]
@michalkvasnicak `generateScopedName` didn't work in `css-loader`.  
My `webpack` version is `1.13.1` and my `css-loader` version is `0.23.1`.  

The client side does output a camelcased class name to the `styles` object, and the class name in the output remains what it is in my css file. I'd prefer the client side output.

**Comment by AmBeta** [comment]
In another word, with `import styles from './style.css'`,  
the client side generates this object:

```
{
	"bordered-box": "style__bordered-box___2hkXK",
	"borderedBox": "style__bordered-box___2hkXK"
};
```

the server side generates this object:

```
{
	"borderedBox": "style__borderedBox___1CfFu"
};
```

**Comment by michalkvasnicak** [comment]
In this case I think you should file an issue in https://github.com/css-modules/css-modules-require-hook because this plugin is just a wrapper and does not contain any logic that has something to do with the `camelCase` nor generated css class names.

**Comment by michalkvasnicak** [comment]
I tried to reproduce the problem in https://github.com/css-modules/css-modules-require-hook/blob/4.0.5/test/api/camelCase.js.

I set `generatedScopedName` + `camelCase` and it seems to work just fine. So I will need to investigate more. Maybe there is some problem when it is used in this plugin.

**Comment by AmBeta** [comment]
@michalkvasnicak Things turn out to be right now and I can't reproduce the problem either. I really have no idea what happened:(  

I'll keep tracking this problem and try to find the cause.

By the way, I use `less` as the preprocessor, and this is my hook file:  

```
// less-require-hook.js
var less = require('less');

module.exports = function processLess(data, filename) {
  var result;
  less.render(data, {}, function (error, output) {
    result = output.css;
  });
  return result.toString('utf8');
};
```

**Comment by michalkvasnicak** [comment]
So is it good now? It seems like some cache problem e.g. If you had a `.borderBox` in css and then you rewrote it to `.border-box` maybe this could cause a problem.

**Comment by AmBeta** [comment]
It works fine now. Maybe the cause is babel cache.
