### ISSUE TITLE
babel-plugin-transform-postcss

### ISSUE THREAD

**Issue by wbyoung** [michalkvasnicak/babel-plugin-css-modules-transform#30]
Hi @michalkvasnicak,

I just wanted to bring your attention to [`babel-plugin-transform-postcss`](https://github.com/wbyoung/babel-plugin-transform-postcss) which I based off of the awesome work that you've done here.

This plugin wasn't quite fitting with what I wanted, so I started from what you had & went in a slightly different direction. The main differences are:

- Doesn't use the `require` hook to run PostCSS
- Supports asynchronous PostCSS plugins
- Uses [`postcss-load-config`](https://github.com/michael-ciniawsky/postcss-load-config) (which appears to be a future standard) to locate `postcss.conf.js`

I still have a few things left that I want to address in the build system that uses it (namely watch support via Browserify which seems similar to #27 here).

**Comment by wbyoung** [comment]
Closing since this was really just to ping @michalkvasnicak.

**Comment by michalkvasnicak** [comment]
@wbyoung Thank you for information 👍 

I hope that this plugin served well as the base for your plugin. :) I will list it in README.

**Comment by wbyoung** [comment]
It did indeed — great work!
