### ISSUE TITLE
Unknown arguments: processOpts

### ISSUE THREAD

**Issue by inv8der** [michalkvasnicak/babel-plugin-css-modules-transform#36]
According to the `css-modules-require-hook` [docs](https://github.com/css-modules/css-modules-require-hook#processoropts-object), processOpts is not a valid option. Should this be processorOpts instead? I receive this error with the former option.

```
const scssParser = require('postcss-scss').parse;

require('babel-register')({
    ignore: /node_modules(?=(.(?!\.(scss|css)$))*$)//,
    plugins: [
        ['css-modules-transform', {
            extensions: ['.css', '.scss'],
            processOpts: { parser: scssParser },
        }],
    ],
});
```

<img width="479" alt="screen shot 2017-02-15 at 4 19 58 pm" src="https://cloud.githubusercontent.com/assets/830026/23001773/919b9b74-f39b-11e6-97ab-2f3a9bb5c0df.png">

**Comment by michalkvasnicak** [comment]
Thank you for report, released as 1.2.1
