### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by guidiego** [michalkvasnicak/babel-plugin-css-modules-transform#37]
I don't know why, but .sass not work :thinking:

**Comment by michalkvasnicak** [comment]
Please provide more information like error log and your configuration.

**Comment by Erid** [comment]
You can fix it by adding `indentedSyntax: true` to the options on the `renderSync`:
```
const sass = require('node-sass')

module.exports = (data, filename) => {
  const result = sass.renderSync({ data, file: filename, indentedSyntax: true }).css

  return result.toString('utf8')
}
```

According to `node-sass`' documentation they use the extension from the filename to know whether to parse the indented syntax or not ([reference](https://github.com/sass/node-sass#indentedsyntax)), but for some reason it isn't working for me either, so I just added that option there and it worked.

**Comment by michalkvasnicak** [comment]
@guidiego is your issue solved? Did @Erid advice help? Can I close this issue?

**Comment by guidiego** [comment]
Yeah! @michalkvasnicak thx :D
