### ISSUE TITLE
Error with Babel 6.24.0

### ISSUE THREAD

**Issue by GreenGremlin** [michalkvasnicak/babel-plugin-css-modules-transform#43]
When used with Babel 6.24.0, I get the following error. I shortened the absolute path to _./node_modules_. Looking at the Babel source, it looks like manipulateOptions was only added in Babel 7.

```
ReferenceError: [BABEL] src/foo/foo.js: Unknown option: ./node_modules/babel-plugin-css-modules-transform/build/index.js.manipulateOptions. Check out http://babeljs.io/docs/usage/options/ for more information about options.
```

I'musing the following custom preset to configure babel-plugin-css-modules-transform.

``` javascript
module.exports = {
    plugins: [
        [require('babel-plugin-css-modules-transform'), {
            extractCss: {
                dir: 'lib',
                filename: '[path]/[name].css',
            },
        }],
    ],
};
```

**Comment by michalkvasnicak** [comment]
Thank you! :) 

This is weird because this project is tested against `babel 6.22.2` so it shouldn't do any BC changes. If you downgrade babel to this version does it solve the problem?
