### ISSUE TITLE
Global/Local CSS imports

### ISSUE THREAD

**Issue by gregorskii** [michalkvasnicak/babel-plugin-css-modules-transform#46]
Hi there,

I am having issues related to this PR in css-modules with this plugin:

https://github.com/css-modules/css-modules/pull/65

I cannot import global (non module) scss files into my css modules files. Per that ticket I solved my server rendering by using webpack loaders, before I was using this library and babel.

I would still like to use this plugin for unit tests that may need to inline css module classnames into the components when running in enzyme. This plugin solves that need for me as long as I do not import global files into the non module css.

Example where it breaks:

```
@import "~client/styles/_vars.global.scss";

.nav {
  width: 96px;
  background-color: $blue;
}
```

Where $blue comes from the `_vars.global.scss`, and that file is not a module.

When using this library and a custom SCSS compiler, the SCSS compiler does not ever emit the result:

scssPreprocessor.js
```
const sass = require('node-sass');

module.exports = function processSass(data, filename) {
  console.log(data, filename);
  const result = sass.renderSync({
    data,
    file: filename
  }).css;
  console.log(result.toString('utf8'));
  return result.toString('utf8');
};
```

Where the second console never runs.

Do you have any ideas of what could solve this? Is there already a solution in the config?

Thanks,

Greg

**Comment by michalkvasnicak** [comment]
Could you create a minimal repository to reproduce your problem? I'm wondering if your `scssPreprocessor.js` throws an error or what is the result. 

Have you tried this solution [postcss-import plugin](https://github.com/css-modules/css-modules/pull/65#issuecomment-188537742) from the PR you linked? You can use it by setting up `append` in your configuration for this plugin or check out [babel-plugin-transform-postcss](https://github.com/wbyoung/babel-plugin-transform-postcss).

**Comment by michalkvasnicak** [comment]
If you want only to have css class names inlined by using webpack, you can look at the configuration I'm using in my [create-js-app config for server side bundling](https://github.com/michalkvasnicak/create-js-app/blob/master/packages/js-app-plugin-universal-webpack/src/config/server/production.js). It compiles css modules without emitting files.

**Comment by michalkvasnicak** [comment]
Other solution is, if you even need to inline css for your tests. If you can ignore them then just use `jest` and [set up mock file loader for css files](https://facebook.github.io/jest/docs/webpack.html).

**Comment by gregorskii** [comment]
I am using it here:

https://github.com/gregorskii/redux-starter/blob/master/test/unit/spec/helpers/sassPreprocessor.js

I cannot use postCSS to compile it I believe, the issue is I have a mix of CSS Modules and non CSS modules. The only way to fix it in Webpack is to have different rules:

```
{
  test: /\.scss$/,
  include: [/\.global/, /bootstrap/],
  loader: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {
        loader: 'css-loader',
        options: { modules: false }
      },
      { loader: 'postcss-loader' },
      { loader: 'sass-loader' }
    ]
  })
},
{
  test: /\.scss$/,
  exclude: [/\.global/, /bootstrap/, /node_modules/],
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {
        loader: 'css-loader',
        options: {
          modules: true,
          importLoaders: 1,
          localIdentName: '[local]--[hash:base64:5]'
        }
      },
      { loader: 'postcss-loader' },
      { loader: 'sass-loader' }
    ]
  })
}
```

This include exclude process cannot be expressed by the config on this plugin, is that correct?

**Comment by michalkvasnicak** [comment]
@gregorskii I'm sorry but it cannot be done this way using this plugin.

**Comment by gregorskii** [comment]
Ok thanks, will use webpack with testing, I found [mocha-webpack](https://www.npmjs.com/package/mocha-webpack) is a good alternative to using something bigger like karma, if one is using Mocha.

Thank you for the aid @michalkvasnicak.
