### ISSUE TITLE
extract generated css in file(s)

### ISSUE THREAD

**Issue by themouette** [michalkvasnicak/babel-plugin-css-modules-transform#5]
I'm wondering if there is a way to collect generated css in the process and generate it in a single file or in separate files.

I'm using [babel-plugin-webpack-loaders](https://github.com/istarkov/babel-plugin-webpack-loaders) for this, but having to setup webpack is a real pain.

**Comment by michalkvasnicak** [comment]
Sorry there is no way to extract generated css to files at the moment. I can't imagine how should something like that work. 

Maybe save css files when babel finishes parsing. 

Do you have any ideas how to do that and how config should look?

**Comment by themouette** [comment]
I do not have deep understanding on how  css-modules-require-hook or postcss works.

Since you asked I looked into both and came up with the genuine idea it is possible to leverage [processorOpts](https://github.com/css-modules/css-modules-require-hook/blob/master/lib/index.js#L99) from css-modules-require-hook and [lazyResult.then](https://github.com/postcss/postcss#js-api) from postcss.

It might require some addition to css-require-module-hook, so I opened https://github.com/css-modules/css-modules-require-hook/issues/65 just to be sure.

**Comment by michalkvasnicak** [comment]
Thank you :) I'll dive into it in the couple of a days or you can if you have time. We need to find hook which babel calls when parsing is finished and our extraction should be there I think.

**Comment by DekusDenial** [comment]
I am using [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl) for one of my projects and like many other babel plugins it extract information during runtime and export them at dedicated location defined in plugin option

see
https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/index.js#L149-L174

**Comment by michalkvasnicak** [comment]
@DekusDenial thank you! I'll take a closer look, but currently I don't have much time. Maybe in next few days I hope.

**Comment by michalkvasnicak** [comment]
Hi. So, I made some changes yesterday in pull request #6. But then I encountered few problems:

- in first build using this babel plugin, we'll create css file / files - OK, but `Program.enter` and `Program.exit` visitors are called for every javascript file processed by babel, so we can easily create css file for each javascript file, but if we want only single file, we need to append contents to existing file (problem 2).
- in second and next builds, how would you clean existing css files from previous builds? If we are using single output css file, we need to append contents to css file, but if it exists, it will just grow bigger.

Do you have any ideas how to solve those problems? Is there any babel hook which we can use to call something on start and finish of whole processing?

**Comment by michalkvasnicak** [comment]
https://github.com/michalkvasnicak/babel-plugin-css-modules-transform/blob/extract-css-to-file/src/index.js#L157 there we can easily save styles for each javascript file.

**Comment by themouette** [comment]
Maybe the concatenation can be done in another part of the build, babel is a transpiler after all, not a bundler.

WDYT?

**Comment by michalkvasnicak** [comment]
Im my projects I am using webpack for client side build and babel for server side. I don't need to extract css using babel in that case. 

What are you proposing is something like a wrapper around babel or something like that if I understand you right. 

Why you need something like that? :) What's your use case?

**Comment by DekusDenial** [comment]
I think @th

**Comment by DekusDenial** [comment]
I think @themouette just want to use a single tool for multiple purposes. I have to set up postcss task to extract css-modules and tweak require hook to work on the server side because I have async postcss plugins, which does not work with css-modules-require-hook. If you do webpack for the client, you won't see that problem because it handles everything with the right loaders in chain

**Comment by themouette** [comment]
Thing is that I want to release a library that uses css-modules.

To do so, whether I  expect the library consumer to use webpack with dedicated sass and css-modules setup, or I provide an ES5/CSS build.

I transform the javascript files through babel, and for now rely on [babel-plugin-webpack-loaders](https://github.com/istarkov/babel-plugin-webpack-loaders) to extract css along the way.
Then I concatenate all the generated css files in a single exported file using `cat dist/*.css dist/main.css`.

I wish I could replace [babel-plugin-webpack-loaders](https://github.com/istarkov/babel-plugin-webpack-loaders) with your plugin [babel-plugin-css-modules-transform](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform) because a new webpack instance is run for each css file, this has a huge overhead.

That's ok if there is several css files generated in the process, I can bundle them in a second step, just as now. Css are already generated by [babel-plugin-css-modules-transform](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform) so a single tool can do the job.

**Comment by michalkvasnicak** [comment]
I see. Ok I'll look into it. Extraction is done, saving css files is the hardest part (not in case of multiple files but if you want to have one single file produced by this plugin). I wish babel had post-hook so I can detect when a transformation is finished.
