### ISSUE TITLE
postCSS usage + autoprefixer plugin

### ISSUE THREAD

**Issue by TroutZen** [michalkvasnicak/babel-plugin-css-modules-transform#52]
Hi,
Thanks for the great plugin. I am wondering however, how I can configure to use postcss and the autoprefixer plugin.

**Comment by michalkvasnicak** [comment]
@TroutZen you can take a look on https://github.com/css-modules/css-modules-require-hook#adding-custom-postcss-plugins we have similar configuration option for babel plugin.

**Comment by michalkvasnicak** [comment]
@TroutZen it uses `postcss` under the hood. Just provide plugins you want to use based on documentation mentioted above.

**Comment by michalkvasnicak** [comment]
@TroutZen also see configuration in https://github.com/michalkvasnicak/babel-plugin-css-modules-transform#installation so you can check how should `prepend` option look :)

**Comment by TroutZen** [comment]
Ah - this is very useful @michalkvasnicak - thanks for the help.

**Comment by TroutZen** [comment]
My working config for any other lost souls...

```
var preprocessCss = require('./sass-loader.js');

// ....

plugins: [
                            [
                                "css-modules-transform", {
                                    "prepend": [ require('autoprefixer') ],
                                    "preprocessCss": preprocessCss,
                                    "generateScopedName": "[name]__[local]__[hash:base64:5]",
                                    "extensions": [".scss"],
                                    // rootDir needed so hashes of css modules equiv on client/server
                                    "rootDir": path.resolve(__dirname, '../', './src')
                                }
                            ]
                        ]
```

**Comment by michalkvasnicak** [comment]
@TroutZen greate! 👍  Thank you 😉

**Comment by danny-andrews** [comment]
How are you doing `require`s in .babelrc? It's a JSON5 file.
