### ISSUE TITLE
extractCss wipes out css file

### ISSUE THREAD

**Issue by lfender6445** [michalkvasnicak/babel-plugin-css-modules-transform#53]
```
// "babel-plugin-css-modules-transform": "^1.2.7",
// .babelrc
{
  "presets": [
    "es2015",
    "react"
  ],
  "plugins": [
    "transform-runtime",
    "transform-decorators-legacy",
    "transform-class-properties",
    "babel-plugin-transform-object-rest-spread",
    [
      "css-modules-transform",
      {
        "camelCase": true,
        "extractCss": "node_modules/flexboxgrid/dist/flexboxgrid.css"
      }
    ]
  ]
}
```

when I run my build command I am noticing the file `node_modules/flexboxgrid/dist/flexboxgrid.css` is mutated into an empty file - is there a way to build using this plugin in a way that is destructive?

**Comment by michalkvasnicak** [comment]
I'm sorry for the late response, not much free time these days.

What should be an expected outcome? Appending to the file? If appending to a file, there is no way to know if you are updating existing declarations or not so every build is going to rewrite the file.
