### ISSUE TITLE
importing from node_modules '~' path

### ISSUE THREAD

**Issue by 3upzorz** [michalkvasnicak/babel-plugin-css-modules-transform#54]
using `@import '~my-module/css/file'` gives me an error on the server side but works fine on my frontend with webpack.

error:

Error: File to import not found or unreadable: ~@my-module/css/file.

When I switch to `@import './node_modules/my-module/css/file'` it works fine.

**Comment by michalkvasnicak** [comment]
@3upzorz yeah, it is because webpack is managing imports itself so it can resolve `~` but in babel can't. Maybe there is a way how to configure `css-modules-require-hook` to do so but I'm not sure.

**Comment by michalkvasnicak** [comment]
If `my-module` is module installed by `npm/yarn` so it is in `package.json` and `node_modules` then I think `@import 'my-module/css/file';` should work.

**Comment by coreyleelarson** [comment]
@michalkvasnicak I am also getting this same error, but importing mine how you suggested. Everything is working just fine, but I'm getting the error during server compilation.

**Comment by michalkvasnicak** [comment]
@coreyleelarson what error are you getting?
