### ISSUE TITLE
Use cmhr.js (if exists)

### ISSUE THREAD

**Issue by danny-andrews** [michalkvasnicak/babel-plugin-css-modules-transform#56]
It'd be nice if you could configure css-modules-require-hook via the [cmrh.js config file](https://github.com/css-modules/css-modules-require-hook#using-with-babel-node--es6-imports). I have a use-case where I need to use a postCSS plugin with options set:
postcss.config.js:
```js
const variables = require('./src/brand/variables');

module.exports = {
  plugins: [
    require('postcss-custom-properties')({ variables }),
  ],
};
```

.babelrc
```js
"plugins": [
  [
    "css-modules-transform",
    {
      "prepend": ["how-do-I-use-my-dynamic-plugin"],
      "generateScopedName": "[name]__[local]___[hash:base64:5]",
      "extensions": [".css"],
      "extractCss": "./dist/app.css"
    }
  ]
]
```
I can't do ` "prepend": [require('postcss-custom-properties')({ variables })]` because .babelrc isn't a js file. If this plugin read from cmrh.js (if it exists) problem would be solved.

**Comment by danny-andrews** [comment]
This would allow you to do a lot more transformations inline, rather than having to write a file which outputs a function for every option you want to use.

**Comment by michalkvasnicak** [comment]
Hello, just create `my-dynamic-plugin.js` somewhere in your project with the code:

```js
const variables = {};

module.exports = function myPlugin() {
  return require('postcss-custom-properties')({ variables });
}
```

And then change `prepend` in your `.babelrc` file to `./my-dynamic-plugin.js` (if the plugin file is in the same directory level as `.babelrc` file.

**Comment by danny-andrews** [comment]
That works. Thanks!
