### ISSUE TITLE
Generating empty css file

### ISSUE THREAD

**Issue by MatthiasBrandt** [michalkvasnicak/babel-plugin-css-modules-transform#58]
Plugin is generating an empty css file:

This is my configuration:

```
...
["css-modules-transform", {
  "extensions": [".css", ".scss", ".less"],
  "extractCss": "./dist/stylesheets/theme.css"
}],
```

I went through the source and my **requires** do get picked up and get transformed but it seems to fail here:

```
if (t.isExpressionStatement(path.parent)) {
  //buildClassNameToScope is working
  var p = path.replaceWith(buildClassNameToScopeNameMap(tokens));
  console.log(p)
  return p; // p = undefined :(
} else {
  path.remove();
}
```
Any idea what could be causing this?

**Comment by michalkvasnicak** [comment]
@MatthiasBrandt could you create a simple project you can share to reproduce this error?

**Comment by taqimustafa** [comment]
@michalkvasnicak I am facing the same issue. This package doesn't seems to be updating the bundle.css file. Anyway to rebuild the file ?

**Comment by jsveron23** [comment]
@michalkvasnicak It seems this plugin couldn't parse 'babel-plugin-module-resolver' alias. After I changed module name with relative path from module alias name, it works well.

**Comment by michalkvasnicak** [comment]
Yes this package doesn't support aliases because of the order the babel plugins are executed. Maybe there is a way how to somehow resolve this after `babel-plugin-module-resolver` does its job but I don't have time to investigate this. But I'm happy to accept the PR for this.
