### ISSUE TITLE
Example with PostCSS?

### ISSUE THREAD

**Issue by FezVrasta** [michalkvasnicak/babel-plugin-css-modules-transform#59]
Hi, this plugin is really awesome and I'd love to use it to bundle a library.

The problem is that I don't seem to understand how to make this work with PostCSS? PostCSS by default has a promise based API. How can it work with `preprocessCss` option?

Also, is the async limitation just because you didn't have time to implement it or is it an actual limitation of the technology you used to create the plugin?

**Comment by michalkvasnicak** [comment]
Hello, 

this plugin is only wrapper around [css-modules-require-hook](https://github.com/css-modules/css-modules-require-hook) that's why it can't use async, because it is used in runtime (during `require`call). 

There is another plugin [babel-plugin-transform-postcss](https://github.com/wbyoung/babel-plugin-transform-postcss), please take a look if it solves your problem :)

**Comment by FezVrasta** [comment]
Hi, thanks for the answer. I tried the one you suggest but it doesn't seem to support extraction of the generated CSS so it's quite useless...

**Comment by michalkvasnicak** [comment]
Yes I see, it is recommended to use postcss-cli to extract styles, using the same config.

Unfortunately my plugin can't do the work with async plugins because of `require` hook limitation.

**Comment by FezVrasta** [comment]
I see, the problem is that transform-postcss suggests to use postcss-cli, but doesn't explain how the hell am I supposed to make the generated class names match... 😩

I already opened an issue in its repo...
https://github.com/wbyoung/babel-plugin-transform-postcss/issues/60

**Comment by FezVrasta** [comment]
Anyway, may you provide an example to use yours with PostCSS without any async plugin? I think it may be enough for my use case.

**Comment by michalkvasnicak** [comment]
PostCSS is already supported, you just need to configure your plugins. You can follow the documentation for `css-modules-require-hook` (for example [Adding custom PostCSS plugins to css-modules-require-hook](https://github.com/css-modules/css-modules-require-hook#adding-custom-postcss-plugins)). The only thing you have to do, is to configure it like so:

1. create a file `prependPostcssPlugin.js` in the root of project with content:
```js
const cssnext = require('cssnext');

module.exports = () => [cssnext()]
```

2. in your `.babelrc` just configure:

```json
"plugins": [
        [
            "css-modules-transform", {
                "prepend": [
                    "./prependPostcssPlugin.js"
                ]
            }
        ]
    ]
```

I haven't tested this code but I think it suffices as an example.

**Comment by michalkvasnicak** [comment]
See whole [available configuration](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform#installation).

**Comment by FezVrasta** [comment]
Thank you!

**Comment by a-x-** [comment]
More accurate working example:
**.babelrc**
```json
```

**prepend-postcss-plugins.js**:
```js
const { plugins } = require('../postcss.config.js');

module.exports = () => {
  return { plugins };
};
```

**Comment by a-x-** [comment]
But it don't allow pass options to postcss. Like `map: 'inline'`

**Comment by a-x-** [comment]
css-modules-transform + postcss + generateScopedName **does not work** as expecting :(

input:
**a.css**:
```css
.foo { color: red; font-weight: bold; }
.bar { color: red; font-weight: normal; }
```
output:
**a.css**:
```css
.foo-XcD0 {font-weight: bold;}
.bar-wEd3 {color: red; font-weight: normal;}
.foo,.bar {color: red;} /* <<< generateScopedName omited in postcss optimized selector */
```
