### ISSUE TITLE
`import './global.css'` does not work

### ISSUE THREAD

**Issue by CrocoDillon** [michalkvasnicak/babel-plugin-css-modules-transform#60]
Hello, I have ~~two~~ one issue.

First issue is while all these work...

```js
import foo from './global.css' // even if not using foo
require('./global.css')
```

...this one doesn't work:

```js
import './global.css'
```

It just gives the following error:

> Module parse failed: global.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

~~Second issue might not be related to this project but is confusing the hell out of me. In `global.css` I tried the following selectors to get some custom properties in:~~

```css
:root {}
:global :root {}
:global(:root) {}
```

~~But none of those work, the whole block just gets ignored and doesn't end up in the bundle.~~

Interesting though is that I _can_ use the custom properties in the `global.css` file, they are just replaced with their values... as I'm typing this I realize it might be CSSNext doing this intentionally 😅

Hope you can help me out, thanks in advance 😁 

Related PR that introduced ES6 import support is #32 by @GabeMedrash.

**Comment by CrocoDillon** [comment]
Actually it seems like there are more issues with the `import` syntax. `import`s in nested components didn't end up in the bundle, `require` seems to work fine.

Hopefully the last one, `@import '../colors.css'` from within `global.css` (where I defined custom properties now) does not work.

**Comment by michalkvasnicak** [comment]
@CrocoDillon this is probably a problem with postcss and not this plugin. This is just a wrapper around `css-modules-require-hook`. Related PR is merged so does it resolve this issue?
