### ISSUE TITLE
Could this plugin work with babel-plugin-module-resolver?

### ISSUE THREAD

**Issue by songlang1994** [michalkvasnicak/babel-plugin-css-modules-transform#61]
Hi, I have a issue here. And this is my case.

.babelrc file

```json
"plugins": [
  ["module-resolver", {
    "alias": {
      "assets": "./src/assets"
    }
  }],

  ["css-modules-transform", {
    "preprocessCss": "./preprocessCss.js",
    "camelCase": true,
    "generateScopedName": "[name]-[hash:16]",
    "extensions": [".scss"]
  }]
]
```

source file

```javascript
import css from 'assets/stylesheets/basic/loading.scss'
import React from 'react'
// ... 
```

I ran babel compile the source code and I got an empty `css` object in compiled file
```javascript
// ...
var css = {}
// ...
```

But if I change the source code to
```javascript
import css from '../../assets/stylesheets/basic/loading.scss'  // use relative path
import React from 'react'
// ... 
```

Then I got the correct `css` object in compiled file
```javascript
// compiled code
var css = {
  'loading-b': 'loading-b-fe5ceece94c6787b',
  'loadingB': 'loading-b-fe5ceece94c6787b'
};
// ...
```

Is there any way to make this plugin work with `babel-plugin-module-resolver`? Thank you.

**Comment by songlang1994** [comment]
I found a way to use webpack for server side. Maybe I don't need this plugin any more.

**Comment by rbalmf** [comment]
I'm having this exact same issue myself and don't want to resort to webpack.  Would be great if there is a way...
