### ISSUE TITLE
Use plugin from webpack

### ISSUE THREAD

**Issue by olegkleiman** [michalkvasnicak/babel-plugin-css-modules-transform#62]
I'm using this plugin from webpack and just wonder why you do not intended to use it on client side at all? What are possible implications of such use?

**Comment by songlang1994** [comment]
I think it's better to use [css-loader](https://github.com/webpack-contrib/css-loader) in webpack.

**Comment by michalkvasnicak** [comment]
@olegkleiman I was using this plugin in the case when the server side code was not compiled using webpack. Otherwise I just use webpack + css-loader both for client and server side.
