### ISSUE TITLE
Prop `className` did not match.

### ISSUE THREAD

**Issue by Skrpk** [michalkvasnicak/babel-plugin-css-modules-transform#63]
Warning: Prop `className` did not match. Server: "Header__selected___3IRlm" Client: "Header__selected__3IRlm"

All classNames, rendered on the server has 3 undersores, but classNames, rendered on the client has 2.

**Comment by michalkvasnicak** [comment]
This is not a problem in this plugin, you should check you configuration if you have the same `className` formats for client and server side.

Maybe paste here your configurations.

**Comment by michalkvasnicak** [comment]
Closing this as there is not activity and it seems just to be misconfigured.
