### ISSUE TITLE
user less @import something error

### ISSUE THREAD

**Issue by chauncey123** [michalkvasnicak/babel-plugin-css-modules-transform#68]
{ [Error: '../style/Theme.less' wasn't found. Tried - ../style/Theme.less,../style/Theme.less]
  type: 'File',
  filename: 'input',
  index: 0,
  line: 1,
  callLine: NaN,
  callExtract: undefined,
  column: 0,
  extract: [ undefined, '@import "../style/Theme.less";', '' ],
  message: '\'../style/Theme.less\' wasn\'t found. Tried - ../style/Theme.less,../style/Theme.less',
  stack: undefined }

 // processLess
const less = require('less');

module.exports = function processLess(data) {
  let css;
  less.render(data, { sync: true }, (e, output) => {
 
    css = output.css;
  });
  return css;
};

**Comment by michalkvasnicak** [comment]
`../style/Theme.less` was not found. If it exists, please look to documentation of `less` library because this doesn't have anything to do with this plugin.
