### ISSUE TITLE
complexRequires and currentConfig problems with "prepend"

### ISSUE THREAD

**Issue by Hadrien-DELAITRE** [michalkvasnicak/babel-plugin-css-modules-transform#7]
Hello!

It seems to be buggy when i define "prepend" configuration like :
```json
["css-modules-transform", { "prepend": ["postcss-cssnext"] }]
```

https://github.com/michalkvasnicak/babel-plugin-css-modules-transform/blob/master/src/index.js#L30

Maybe you have to clone `currentConfig` otherwise you will overwrite all values during the rest of the process.

When we log the value of `currentConfig`, we can see the following output for the first file:
```js
{ generateScopedName: '[name]__[local]___[hash:base64:5]',
  prepend: [ 'postcss-cssnext' ] }
```
Then we can see the following output for the second file:
```js
{ generateScopedName: '[name]__[local]___[hash:base64:5]',
  prepend:
   [ Processor {
       version: '5.0.14',
       plugins: [Object],
       postcssPlugin: 'postcss-cssnext',
       postcssVersion: '5.0.14' } ] }
```

Finally we got the throwing message :
```sh
Configuration 'prepend' has to be valid path to a module at index 0 or it does not export a function.
```

Its weird that "prepend" has been updated no ?

**Comment by michalkvasnicak** [comment]
Hello, I'm sorry for the delay. I'll take a look in the next few days, really busy these days.

**Comment by michalkvasnicak** [comment]
Thank you! Added little performance optimization too.

**Comment by Hadrien-DELAITRE** [comment]
Wow cool :+1: I will try this today !
Thanks :)
