### ISSUE TITLE
Add support for the `resolve` option

### ISSUE THREAD

**Issue by pascalduez** [michalkvasnicak/babel-plugin-css-modules-transform#76]
Hi,

recent versions of `css-modules-require-hook` changed  the [resolving mechanism](https://github.com/css-modules/css-modules-require-hook/releases) on the same semver range, and as a consequence most of our unit test broke... 

Apparently the [`resolve`](https://github.com/css-modules/css-modules-require-hook#resolve-object) option was introduced to be able to address this, but is not yet supported/passed by this plugin ?

**Comment by michalkvasnicak** [comment]
Hello, sorry for late response, I don't much free time these days. Maybe I will get some free time on weekend but no promises. PR is welcome :)
