### ISSUE TITLE
babel-plugin-css-modules-transform and css-loader create different class names

### ISSUE THREAD

**Issue by b-ponomarenko** [michalkvasnicak/babel-plugin-css-modules-transform#94]
I have repo (https://github.com/b-ponomarenko/react-boilerplate) where I try to compile css on server using babel-plugin-css-modules-transform (I have the same `generateScopedName` setting) and I note, that when I run compiling process separately on client and on server I have different hash names, example:
for:
```css
.foo {
  background: red;
}
```
server: `{ foo: ‘Foo__foo__-Pwji’ }`
client: `{foo: "Foo__foo__1ZdkW"}`

When I run this processes together hash name from server appears to client bundle, and `style-loader` don't create styles in runtime. What could be wrong?

**Comment by edwardfxiao** [comment]
@b-ponomarenko what fix this?

**Comment by MaheshSinghSawant** [comment]
im facing the same issue. @b-ponomarenko how did you resolve this?

**Comment by edwardfxiao** [comment]
@MaheshSinghSawant Take a look at my solution https://github.com/webpack-contrib/css-loader/issues/877#issuecomment-514461524
